# Generated by Django 2.0.13 on 2019-08-08 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ybsearch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchvideo',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
